<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5ZCQ5qe95ZqS');
$cfg_Cs[7]=array(0,1,0,'5Zyo57q/55WZ6KiA');
$cfg_Cs[11]=array(10,1,1,'5pyA54uX5bGO55qE5byA5Y+R6K+t6KiA');
$cfg_Cs[5]=array(0,1,1,'5Y+R6KGo');
$cfg_Cs[6]=array(0,1,1,'5Lya5ZGY5Lit5b+D');
$cfg_Cs[8]=array(0,1,0,'5pud5bel6LWE');
$cfg_Cs[10]=array(0,1,1,'54Ot6Zeo6K+d6aKY');
$cfg_Cs[12]=array(10,1,1,'56iL5bqP5ZGY5rS76K+l5Y2V6Lqr');
?>