
<field:company itemname="公司名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:company>

<field:position itemname="职位名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:position>

<field:year itemname="工作年限" autofield="1" type="int" isnull="true" default=""  maxlength="250" page="">
</field:year>

<field:salary itemname="税前工资" autofield="1" type="int" isnull="true" default=""  maxlength="250" page="">
</field:salary>

<field:class itemname="职级（如有）" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:class>

<field:language itemname="开发语言" autofield="1" type="checkbox" isnull="true" default="PHP,Java,Python,.NET,C#,C/C++,Ruby,hadoop,node.js,Flash,HTML5,JavaScript,Android,iOS,Windows Phone,COCOS2D-X,Unity3D,Swift,数据库开发,数据挖掘"  maxlength="250" page="">
</field:language>



<field:city itemname="城市" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:city>

<field:date itemname="日期" autofield="1" type="datetime" isnull="true" default=""  maxlength="250" page="">
</field:date>
