<dl id="dl_[field:id/]">
                        <dt id="dt_[field:id/]"><a id="a_[field:id/]" target="_blank" href="[field:arcurl/]">
                            <img src="[field:picname/]" alt="[field:fulltitle/]" width="160" height="140" border="0">
                        </a></dt>
                        <dd>
                            <a target="_blank" href="[field:arcurl/]">
                               [field:title/]
                            </a>
                        </dd>
                    </dl>