
<field:company itemname="公司名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:company>

<field:position itemname="职位名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:position>

<field:year itemname="工作年限" autofield="1" type="int" isnull="true" default=""  maxlength="250" page="">
</field:year>

<field:salary itemname="税前工资" autofield="1" type="int" isnull="true" default=""  maxlength="250" page="">
</field:salary>

<field:class itemname="职级（如有）" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:class>
