
      <a href='[field:link/]'>[field:tag /]</a>
<a href="/tags.php">更多...</a>
</div>
</div>
<div class="shadow"></div>
<div class="sponsor">
AD
</div>
<div class="shadow"></div>
<div class="sitelink">
<h3>友情链接</h3>
<div class="content">
{dede:flink linktype='2' row='100'}[field:link /]{/dede:flink}
</div>
</div>
<div class="shadow"></div>
<div id="box">
<div id="float" class="div1">
<div id="float-ad" class="sponsor">
AD
</div>
<div class="shadow"></div>
<div class="toolbar">
<a href="#top" class="back">回到顶部</a><a href="javascript:showSuggestForm()" class="feedback">意见建议</a>
</div>
</div>
</div>
</div>
<div class="baidu-sponsor">
AD
</div>
</div>
</div>
{dede:include filename="foot.htm"